name: Monthly OFF report

on:
  workflow_dispatch:
  schedule:
    # 03:00 UTC, 1st day of each month
    - cron: "0 3 1 * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update cache (recent)
        run: |
          python -m off_cache.update --country fr --recent-pages 20 --page-size 200

      - name: Build static report (docs/)
        run: |
          python scripts/build_report.py --out docs --limit 200000

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
