name: Monthly OFF report

on:
  workflow_dispatch:
  schedule:
    # 03:00 UTC, 1st day of each month
    - cron: "0 3 1 * *"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update cache (recent)
        run: |
          python -m off_cache.update --country fr --recent-pages 20 --page-size 200

      - name: Build static report (docs/)
        run: |
          python scripts/build_report.py --out docs --limit 200000

      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update monthly report" || echo "No changes to commit"
          git push
